[package]
edition = "2021"
name = "tonbo_marco"
version = "0.0.1"
documentation = "https://docs.rs/tonbo_marco"
license       = "Apache-2.0"
description   = "TonboRecord marco"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "2"

[lib]
path = "src/lib.rs"
proc-macro = true
