name: Bug report
description: Create a report to help us improve
labels: bug
body:
  - type: textarea
    attributes:
      label: What is the current behavior?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is your expected behavior?
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to reproduce it?
    validations:
      required: true
