name: Feature request
description: Suggest an idea for this project
labels: enhancement
body:
  - type: textarea
    attributes:
      label: What is the current behavior?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is your expectation?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why we need this feature?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Are there any alternatives?
    validations:
      required: false
  - type: textarea
    attributes:
      label: What other existing implementations can be used as reference?
    validations:
      required: false
