name: Feature request
description: Suggest an idea for this project
labels: enhancement
body:
  - type: textarea
    attributes:
      label: What is the current issue?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is your solution?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What does this improve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Are there any alternatives?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Does it have a reference?
    validations:
      required: false
